<h1>Create Product</h1>

<form method="POST" action="<?=$this->url('application',['action' => 'create'])?>">
    <div class="form-group">
        <label for="name">Name:</label>
        <input type="text" id="name" name="name" class="form-control">
    </div>
    <div class="form-group">
        <label for="price">Price:</label>
        <input type="text" id="price" name="price" class="form-control">
    </div>
    <div class="form-group">
        <label for="description">Description:</label>
        <textarea name="description" id="description" class="form-control"></textarea>
    </div>
    <div class="form-group">
        <input type="submit" value="Add" class="btn btn-primary">
    </div>
</form>