<h1>Edit Product</h1>

<form method="POST" action="<?=$this->url('application', ['action' => 'edit'])?>">
    <input type="hidden" name="id" value="<?=$product->getId()?>">
    <div class="form-group">
        <label for="name">Name:</label>
        <input type="text" id="name" name="name" class="form-control" value="<?=$product->getName()?>">
    </div>
    <div class="form-group">
        <label for="price">Price:</label>
        <input type="text" id="price" name="price" class="form-control" value="<?=$product->getPrice()?>">
    </div>
    <div class="form-group">
        <label for="description">Description:</label>
        <textarea name="description" id="description" class="form-control"><?=$product->getDescription()?></textarea>
    </div>
    <div class="form-group">
        <input type="submit" value="Edit" class="btn btn-primary">
    </div>
</form>