<h1>Products list</h1>

<table class="table table-striped">
    <thead>
        <tr>
            <th>Name</th>
            <th>Price</th>
            <th>Description</th>
            <th>Actions</th>
        </tr>
    </thead>
    <tbody>
        <?php foreach($products as $product):?>
        <tr>
            <td><?=$product->getName()?></td>
            <td><?=$product->getPrice()?></td>
            <td><?=$product->getDescription()?></td>
            <td>
                <form action="<?=$this->url('application', ['action' => 'remove'])?>" method="POST">
                <a class="btn btn-info" href="<?=$this->url('application', ['action' => 'edit','id' => $product->getId()])?>">Edit</a>
                    <input type="hidden" name="id" value="<?=$product->getId()?>">
                    <button class="btn btn-danger" onclick="alert('are you sure?')">Remove</button>
                </form>
            </td>
        </tr>
        <?php endforeach ?>
    </tbody>
</table>