<!DOCTYPE html>
<html lang="pt-br">
<head>
    <meta charset="UTF-8">
    <title>Product Project</title>
    <!-- Le styles -->
        <?php 
            echo $this->headLink()
            ->prependStylesheet($this->basePath('css/style.css'))
            ->prependStylesheet($this->basePath('css/bootstrap-theme.min.css'))
            ->prependStylesheet($this->basePath('css/bootstrap.min.css'));
    
    echo $this->headScript()
        ->prependFile($this->basePath('js/jquery.min.js'))
        ->prependFile($this->basePath('js/bootstrap.min.js'))
        ?>

</head>
<body>
    <header>
        <nav class="navbar navbar-default">

            <div class="navbar-header">
                <a href="/" class="navbar-brand">Kunstee</a>
            </div>

            <ul class="nav navbar-nav">
                <li><a href="<?=$this->url('application', ['action' => 'Index'])?>">Product's list</a></li>
                <li><a href="<?=$this->url('application', ['action' => 'create'])?>">Create Product</a></li>
            </ul>
        </nav>
    </header>
    <main>
        <div class="content">
            <?php $this->flashHelper(); ?>
            <?=$this->content?>
        </div>
    </main>
    <footer class="footer">
        All rights reserved
    </footer>
</body>
</html>